<a href="https://colab.research.google.com/github/ishaangarg03/Daily_Diary/blob/main/day_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pandas
import pandas as pd
import numpy as np

l1 = [1,2,3,4,5,6]
labels = ["a","b","c","d","e","f"]
d1 = {"A":10,"B":20,"c":30,"D":40,"E":50}
s1 = pd.Series(l1)
s1[4]
s2 = pd.Series(labels)
s2
s3 = pd.Series(l1,labels)
print(s3[0])
print(s3["a"])


1
1


In [ ]:
arr = np.random.randint(1,100,(5,6))
print(arr)
print(type(arr))


[[72 74 90 60 33  9]
 [45  7 33  3 22 68]
 [70 86  7 30 67  2]
 [80 35 80 99 95 43]
 [86 24 19 57 60 94]]
<class 'numpy.ndarray'>


In [ ]:

pdf = pd.DataFrame(arr)
print(pdf)
print(type(pdf))

    0   1   2   3   4   5
0  72  74  90  60  33   9
1  45   7  33   3  22  68
2  70  86   7  30  67   2
3  80  35  80  99  95  43
4  86  24  19  57  60  94
<class 'pandas.core.frame.DataFrame'>


In [ ]:
adf = pd.DataFrame(arr,index=["A","B","C","D","E"],columns=["a","b","c","d","e","f"])
print(df)
print(type(df))

          Id         EmployeeName  \
0          1       NATHANIEL FORD   
1          2         GARY JIMENEZ   
2          3       ALBERT PARDINI   
3          4    CHRISTOPHER CHONG   
4          5      PATRICK GARDNER   
...      ...                  ...   
19918  19919    STEPHANI THOMPSON   
19919  19920      CYNTHIA VASQUEZ   
19920  19921       SANDA WIN THAW   
19921  19922  CHARLES BRIDGEWATER   
19922  19923      DIMITRI SHIKALO   

                                             JobTitle    BasePay  OvertimePay  \
0      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                     CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                     CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3                WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4        DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   
...                                               ...        ...     

In [ ]:
df = pd.read_csv("/Salaries.csv")
df.head()
df.tail()

Id         EmployeeName                             JobTitle  \
19918  19919    STEPHANI THOMPSON                      PRINCIPAL CLERK   
19919  19920      CYNTHIA VASQUEZ                EXECUTIVE SECRETARY I   
19920  19921       SANDA WIN THAW  MENTAL HEALTH REHABILITATION WORKER   
19921  19922  CHARLES BRIDGEWATER                       ASPHALT WORKER   
19922  19923      DIMITRI SHIKALO                                  NaN   

        BasePay  OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  \
19918  63538.40         0.00      0.00       NaN  63538.40          63538.40   
19919  63538.40         0.00      0.00       NaN  63538.40          63538.40   
19920  58689.87      3398.39   1448.11       NaN  63536.37          63536.37   
19921  57408.59      3227.92   2898.46       NaN  63534.97          63534.97   
19922       NaN          NaN       NaN       NaN       NaN               NaN   

         Year  Notes         Agency  Status  
19918  2011.0    NaN  San Francisco     NaN  
19919  2011.0    NaN  San Francisco     NaN  
19920  2011.0    NaN  San Francisco     NaN  
19921  2011.0    NaN  San Francisco     NaN  
19922     NaN    NaN            NaN     NaN

In [ ]:
df.sample(5)

Id   EmployeeName                                JobTitle  \
813      814  CLIFFORD COOK      INSPECTOR III, (POLICE DEPARTMENT)   
9290    9291  ENDIA COSTLEY                        REGISTERED NURSE   
16873  16874   NINA MARILLO  EMPLOYMENT AND TRAINING SPECIALIST III   
16119  16120   BASIL CANION                        POLICE OFFICER I   
7939    7940  DIANE ROBBINS                      NURSE PRACTITIONER   

         BasePay  OvertimePay  OtherPay  Benefits   TotalPay  \
813    130481.59     19391.55  25686.52       NaN  175559.66   
9290    81455.85      4450.50  15364.04       NaN  101270.39   
16873   71777.27         0.00      0.00       NaN   71777.27   
16119   12033.10     13160.61  48717.06       NaN   73910.77   
7939   103195.93         0.00   4416.20       NaN  107612.13   

       TotalPayBenefits    Year  Notes         Agency  Status  
813           175559.66  2011.0    NaN  San Francisco     NaN  
9290          101270.39  2011.0    NaN  San Francisco     NaN  
16873          71777.27  2011.0    NaN  San Francisco     NaN  
16119          73910.77  2011.0    NaN  San Francisco     NaN  
7939          107612.13  2011.0    NaN  San Francisco     NaN

In [ ]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [ ]:
df.shape #(rows, columns)

(19923, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19923 entries, 0 to 19922
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                19923 non-null  int64  
 1   EmployeeName      19923 non-null  object 
 2   JobTitle          19922 non-null  object 
 3   BasePay           19922 non-null  float64
 4   OvertimePay       19922 non-null  float64
 5   OtherPay          19922 non-null  float64
 6   Benefits          0 non-null      float64
 7   TotalPay          19922 non-null  float64
 8   TotalPayBenefits  19922 non-null  float64
 9   Year              19922 non-null  float64
 10  Notes             0 non-null      float64
 11  Agency            19922 non-null  object 
 12  Status            0 non-null      float64
dtypes: float64(9), int64(1), object(3)
memory usage: 2.0+ MB


In [ ]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  Benefits  \
count  19923.000000   19922.000000   19922.000000   19922.000000       0.0   
mean    9962.000000   92255.348969    7530.573242    5648.998218       NaN   
std     5751.419042   28327.434413   13274.180963   10020.889674       NaN   
min        1.000000       0.000000       0.000000       0.000000       NaN   
25%     4981.500000   69623.660000       0.000000     115.100000       NaN   
50%     9962.000000   86840.000000    1802.030000    2200.000000       NaN   
75%    14942.500000  107117.437500    9335.012500    7558.552500       NaN   
max    19923.000000  294580.020000  245131.880000  400184.250000       NaN   

            TotalPay  TotalPayBenefits     Year  Notes  Status  
count   19922.000000      19922.000000  19922.0    0.0     0.0  
mean   105434.920430     105434.920430   2011.0    NaN     NaN  
std     34346.626377      34346.626377      0.0    NaN     NaN  
min     63534.970000      63534.970000   2011.0    NaN     NaN  
25%     78304.182500      78304.182500   2011.0    NaN     NaN  
50%     97414.115000      97414.115000   2011.0    NaN     NaN  
75%    124353.317500     124353.317500   2011.0    NaN     NaN  
max    567595.430000     567595.430000   2011.0    NaN     NaN

In [ ]:
adf = pd.DataFrame(arr,index=["A","B","C","D","E"],columns=["a","b","c","d","e","f"])
adf["a"]
adf[["a","b","c","d"]]

a   b   c   d
A  72  74  90  60
B  45   7  33   3
C  70  86   7  30
D  80  35  80  99
E  86  24  19  57

In [ ]:
adf.loc["C"]

a    70
b    86
c     7
d    30
e    67
f     2
Name: C, dtype: int64

In [ ]:
adf.loc[["A","B"]]

a   b   c   d   e   f
A  72  74  90  60  33   9
B  45   7  33   3  22  68

In [ ]:
adf.iloc[2]

a    70
b    86
c     7
d    30
e    67
f     2
Name: C, dtype: int64

In [ ]:
adf['new'] = [10,20,30,40,50]
adf

a   b   c   d   e   f  new
A  72  74  90  60  33   9   10
B  45   7  33   3  22  68   20
C  70  86   7  30  67   2   30
D  80  35  80  99  95  43   40
E  86  24  19  57  60  94   50

In [ ]:
adf['new'] = [100,200,300,400,500]
adf

a   b   c   d   e   f  new
A  72  74  90  60  33   9  100
B  45   7  33   3  22  68  200
C  70  86   7  30  67   2  300
D  80  35  80  99  95  43  400
E  86  24  19  57  60  94  500

In [ ]:
adf.drop("new", axis=1)
adf

a   b   c   d   e   f  new
A  72  74  90  60  33   9  100
B  45   7  33   3  22  68  200
C  70  86   7  30  67   2  300
D  80  35  80  99  95  43  400
E  86  24  19  57  60  94  500

In [ ]:
adf.drop('new',inplace=True,axis=1)
adf

a   b   c   d   e   f
A  72  74  90  60  33   9
B  45   7  33   3  22  68
C  70  86   7  30  67   2
D  80  35  80  99  95  43
E  86  24  19  57  60  94

In [ ]:
adf["a"]%2 == 0

A     True
B    False
C     True
D     True
E     True
Name: a, dtype: bool

In [ ]:
adf[adf["a"]%2 == 0]

a   b   c   d   e   f
A  72  74  90  60  33   9
C  70  86   7  30  67   2
D  80  35  80  99  95  43
E  86  24  19  57  60  94

In [ ]:
adf[adf["a"]%2 == 0]['a']

A    72
C    70
D    80
E    86
Name: a, dtype: int64

In [ ]:
adf[adf["a"]%2 == 0 & (adf["a"]<10)]

a   b   c   d   e   f
A  72  74  90  60  33   9
C  70  86   7  30  67   2
D  80  35  80  99  95  43
E  86  24  19  57  60  94

In [ ]:
adf.reset_index()

index   a   b   c   d   e   f
0     A  72  74  90  60  33   9
1     B  45   7  33   3  22  68
2     C  70  86   7  30  67   2
3     D  80  35  80  99  95  43
4     E  86  24  19  57  60  94

In [ ]:
adf.reset_index(inplace=True)
adf

level_0 index   a   b   c   d   e   f
0        0     A  72  74  90  60  33   9
1        1     B  45   7  33   3  22  68
2        2     C  70  86   7  30  67   2
3        3     D  80  35  80  99  95  43
4        4     E  86  24  19  57  60  94

In [ ]:
adf['states'] = "PB HR HP DL MP".split()
adf

level_0 index   a   b   c   d   e   f states
0        0     A  72  74  90  60  33   9     PB
1        1     B  45   7  33   3  22  68     HR
2        2     C  70  86   7  30  67   2     HP
3        3     D  80  35  80  99  95  43     DL
4        4     E  86  24  19  57  60  94     MP

In [ ]:
adf
# adf.set_index('states')

states  level_0 index   a   b   c   d   e   f
0     PB        0     A  72  74  90  60  33   9
1     HR        1     B  45   7  33   3  22  68
2     HP        2     C  70  86   7  30  67   2
3     DL        3     D  80  35  80  99  95  43
4     MP        4     E  86  24  19  57  60  94

In [ ]:
d = {'a':[1,2,3,np.nan],
     "b":[5,np.nan,np.nan,np.nan],
     "c":[10,20,30,40],
     "d":[np.nan,np.nan,np.nan,np.nan]}
df = pd.DataFrame(d)
df

a    b   c   d
0  1.0  5.0  10 NaN
1  2.0  NaN  20 NaN
2  3.0  NaN  30 NaN
3  NaN  NaN  40 NaN

In [ ]:
pd.isnull(df)

a      b      c     d
0  False  False  False  True
1  False   True  False  True
2  False   True  False  True
3   True   True  False  True

In [ ]:
df.isnull().sum()

a    1
b    3
c    0
d    4
dtype: int64

In [ ]:
df.dropna(axis=1)

c
0  10
1  20
2  30
3  40

In [ ]:
df.dropna(axis=1,thresh=3)

a   c
0  1.0  10
1  2.0  20
2  3.0  30
3  NaN  40

In [ ]:
df


a    b   c   d
0  1.0  5.0  10 NaN
1  2.0  NaN  20 NaN
2  3.0  NaN  30 NaN
3  NaN  NaN  40 NaN

In [ ]:
df.fillna(value=0)

a    b   c    d
0  1.0  5.0  10  0.0
1  2.0  0.0  20  0.0
2  3.0  0.0  30  0.0
3  0.0  0.0  40  0.0

In [ ]:
d2 = {"company":["fb","google","ibm","microsoft","fb"],
      "Employee":["joey","chandler","ross","rachel","monica"]}
df2 = pd.DataFrame(d2)
df2

company  Employee
0         fb      joey
1     google  chandler
2        ibm      ross
3  microsoft    rachel
4         fb    monica

In [ ]:
df2.groupby("company")